# Generated by Django 4.2.1 on 2023-06-05 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categaory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('date2', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('categaory_name', models.CharField(max_length=100)),
                ('categaory_image', models.ImageField(upload_to='mycategaory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('date2', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('product_type_name', models.CharField(max_length=100)),
                ('product_type_image', models.ImageField(upload_to='myproduct_type')),
                ('Categaory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_categaory', to='testapp.categaory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('date2', models.DateField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type_image', models.ImageField(upload_to='myproduct_type')),
                ('product_price', models.CharField(max_length=100)),
                ('product_discription', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_producttype', to='testapp.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leval2_Stage2_Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('date2', models.DateField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type_image', models.ImageField(upload_to='myproduct_type')),
                ('product_price', models.CharField(max_length=100)),
                ('product_discription', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Leval2_Stage1_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_Leval2_Stage1_Product', to='testapp.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
