# Generated by Django 4.2.1 on 2023-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leval2_stage2_product',
            name='product_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leval2_stage2_product',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leval2_stage2_product',
            name='product_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leval2_stage2_product',
            name='product_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='myproduct_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='myproduct_type'),
        ),
    ]
